### ISSUE TITLE
This is seriously emberessing for you, smorenitez.

### ISSUE THREAD

**Issue by IncognitoTGT** [smorenitez/Better-EdPuzzle-Skipper#1]
Oh my god. You are literally one of the dumbest people to ever exist. Like, you think that @ading2210 is your slave and must always work. Then, you say it's broken, and even though you say you can program, you instead decide to bash him. 

Then, you supposedly made a repo, but then it turns out you just skidded his code, including the comments. 

# grow up

**Comment by silvereengames** [comment]
bro what quit yapping

**Comment by kxtzownsu** [comment]
close this 🤦‍♀️

**Comment by LolzTheDev** [comment]
this sersly emberes
(lets actualy stop heress him now)
