### ISSUE TITLE
Uses Stolen Code That Doesn't Even Work

### ISSUE THREAD

**Issue by IAGOnGithub** [smorenitez/Better-EdPuzzle-Skipper#10]
You just copied "your" code from [your previous issue on ading's repo.](https://github.com/ading2210/edpuzzle-answers/issues/37#issue-2128082927) Which he noted didn't even work.

**Comment by smorenitez** [comment]
I have tested *my* code over 5 times and it has worked every single time. Unless you send me video proof of you using my script (from this github), Feburary 11th 2024 version, and it not skipping the video, then your lying. The video skipping feature ONLY unlocks the progress bar and does not answer all questions. Question Answer AI is coming soon.

**Comment by smorenitez** [comment]
@IAGOnGithub

**Comment by genericness** [comment]
> You just copied "your" code from [your previous issue on ading's repo.](https://github.com/ading2210/edpuzzle-answers/issues/37#issue-2128082927) Which he noted didn't even work.
