### ISSUE TITLE
Uses Stolen Code

### ISSUE THREAD

**Issue by IAGOnGithub** [smorenitez/Better-EdPuzzle-Skipper#11]
#10 was incorrectly closed. The code in question is confirmed to be stolen; pull up a diff tool, check against ading's code, and it is so blatantly stolen that it's embarrassing. You didn't even remove the whitespace properly.
Now I understand why my computer science teacher spent ages talking about copyright law. Apparently kids don't understand that shit at all.

**Comment by genericness** [comment]
it WAS gpl compliant, idk if it is now

**Comment by smorenitez** [comment]
I will add the GPL thing in 3 weeks

**Comment by IAGOnGithub** [comment]
> I will add the GPL thing in 3 weeks

This code is technically GPL compliant, but only because it doesn't change anything whatsoever. Again, the code is stolen and basically unmodified, aside from stripping out newlines.

**Comment by smorenitez** [comment]
> This code is technically GPL compliant, but only because it doesn't change anything whatsoever. Again, the code is stolen and basically unmodified, aside from stripping out newlines.
Ok then problem solved why did you even open this issue ????????

**Comment by IAGOnGithub** [comment]
Because it is stolen code that you pretend is yours. That IS a violation of copyright law.

**Comment by smorenitez** [comment]
> Because it is stolen code that you pretend is yours. That's a violation of copyright law. It's so obviously illegal that I don't think the GPL even mentions it.

k then sue me lol

**Comment by smorenitez** [comment]
Kindly refrain from altering the title to one that may be perceived as misleading, or I will be compelled to close the GitHub thread.
-smorenitez.

**Comment by IAGOnGithub** [comment]
The title is not misleading.
