### ISSUE TITLE
Still does not work

### ISSUE THREAD

**Issue by Paste11** [smorenitez/Better-EdPuzzle-Skipper#14]
I dont know how you tested it but im trying to use it on my computer right now and it is not working

**Comment by smorenitez** [comment]
Send video proof or your lying.

**Comment by IAGOnGithub** [comment]
Result of running the script:
![215 on a white background](https://github.com/smorenitez/Better-EdPuzzle-Skipper/assets/122576313/3928c5a8-4288-438a-b67b-4c415f8f48d0)

**Comment by smorenitez** [comment]
Still not a video. I dont believe you. It works for me.

**Comment by IAGOnGithub** [comment]
@smorenitez consider posting a video of it working on your computer.

**Comment by smorenitez** [comment]
@IAGOnGithub 

https://github.com/smorenitez/Better-EdPuzzle-Skipper/assets/152504256/5aded268-3e64-4486-bc80-97e9f4b9f777

**Comment by IAGOnGithub** [comment]
> 2024-02-11.00-35-45.mp4

Doesn't play.

**Comment by smorenitez** [comment]
Closed. He is trolling.

**Comment by IAGOnGithub** [comment]
Are you trolling, @smorenitez?

**Comment by lvxnull** [comment]
@IAGOnGithub i got it to play by right clicking, saving and then opening locally with mpv
