### ISSUE TITLE
Using as a Bookmarklet Doesn't Work

### ISSUE THREAD

**Issue by IAGOnGithub** [smorenitez/Better-EdPuzzle-Skipper#16]
The script appears to work correctly when ran directly in the console, but not as a bookmarklet.

The result of running it as a bookmarklet looks something like this: ![image](https://github.com/smorenitez/Better-EdPuzzle-Skipper/assets/122576313/aaf26cf5-d3b9-40a2-b4e2-ea44da74e144)

**Comment by IAGOnGithub** [comment]
The number that is displayed doesn't seem to be random, but I can't predict it.

**Comment by lvxnull** [comment]
That number is the return value of `requestAnimationFrame` that happens to be on the last line of the file. In order to fix this, wrap the code in a immediately executed lambda function and use `void` to make sure the expression always produces `undefined`, like this:
```javascript
void (function() {
  // code goes here
}());
```

**Comment by IAGOnGithub** [comment]
> That number is the return value of `requestAnimationFrame` that happens to be on the last line of the file. In order to fix this, wrap the code in a immediately executed lambda function:
> 
> ```js
> javscript:(() => {
>   // code goes here
> })();
> ```
> 
> You could also use a void expression so that even if you return something from the lambda by accident it won't overwrite the page.

This patch works and has been merged.
