### ISSUE TITLE
Still Uses Stolen Code, #11 Still Not Resolved

### ISSUE THREAD

**Issue by IAGOnGithub** [smorenitez/Better-EdPuzzle-Skipper#17]

**Comment by smorenitez** [comment]
1. It does not use stolen code.
2. It is "technically GPL compliant"
Do not open future issues.

**Comment by IAGOnGithub** [comment]
This issue was wrongly closed. The video skipping code is objectively taken from somewhere else without attribution. It is also not compliant with the GPL as it needs to provide attribution and be licensed under a compatible license.

**Comment by smorenitez** [comment]
> This issue was wrongly closed. The video skipping code is objectively taken from somewhere else without attribution. It is also not compliant with the GPL as it needs to provide attribution and be licensed under a compatible license.

Smd pussy

**Comment by IAGOnGithub** [comment]
The copyright holder of the original code could sue you.

**Comment by smorenitez** [comment]
> The copyright holder of the original code could sue you.

its open source idiot anyone can copy it right now if they wanted to

**Comment by IAGOnGithub** [comment]
You clearly do not understand how open source works. If I just reposted what you made and took the credit for myself, guess what? That wouldn't be okay!
