### ISSUE TITLE
Copyright Violation Issue: Utilizing Code That Is Stolen

### ISSUE THREAD

**Issue by IAGOnGithub** [smorenitez/Better-EdPuzzle-Skipper#18]
This software is NOT GPL compliant; it must be licensed under a GPL-compatible license and provide proper attribution to the original author of the code, ading. Therefore, the software is at risk of being taken down for copyright violations.

**Comment by IAGOnGithub** [comment]
See #5, #10, #11, #17.

**Comment by smorenitez** [comment]
Sue me pussy you won't

**Comment by CozyAraka** [comment]
Bro literally just stole code and told a random guy hes a pussy while being a dick about it💀

**Comment by IntelligentPickle** [comment]
little bro violated one of the basic components of the open source community and told a guy to suck one over it LMAO

**Comment by lvxnull** [comment]
I don't know if you realize, but the person who made the code doesn't need to sue you in order to take down your repo.

**Comment by smorenitez** [comment]
> I don't know if you realize, but the person who made the code you stole doesn't need to sue you in order to take down your repo.

I have an offline copy thats on my SSD so even if it does get taken down i will just make a new github repo with that fucking licensing shit lol i cant be bothered to do it now

**Comment by IAGOnGithub** [comment]
You are required to do "that fucking licensing shit" or else you are at risk of potential legal action.

**Comment by smorenitez** [comment]
Ok well I am planning on doing it in a future update. it is planned but not a priority. I don't know how to tell you this but you won't understand when I keep telling you.

**Comment by smorenitez** [comment]
So let me know or like what because you keep opening issues and this is seriously mad annoying like stop it.

**Comment by dj1ch** [comment]
> So let me know or like what because you keep opening issues and this is seriously mad annoying like stop it.

well ofc it is bc its an issue that your code is stolen, and probably needs to be fixed before the repo owner(s) take action. you not wanting to implement these fixes right away just digs yourself into a deeper hole. github is no joke.

**Comment by smorenitez** [comment]
Stfu

**Comment by smorenitez** [comment]
Go away lol

**Comment by smorenitez** [comment]
If you dont have an edpuzzle dont visit my project.

**Comment by smorenitez** [comment]
Like tf?

**Comment by smorenitez** [comment]
Bye.

**Comment by dj1ch** [comment]
@meghan06 @smorenitez you guys should shut up and kiss or smt lmao

**Comment by IntelligentPickle** [comment]
> Bye.

BLUD STOP STACKING YOU’RE BEING SO ANNOYING

**Comment by UrkiMimi** [comment]
Also this code is horrendously bad. Please take a Computer Science class.

**Comment by TopchetoEU** [comment]
interesting that he put this in his shitty ChatGPT replit:

![image](https://github.com/smorenitez/Better-EdPuzzle-Skipper/assets/36534413/93cdf6dd-4bb2-4292-8055-b699e80bd0d1)

**Comment by IAGOnGithub** [comment]
> Ok well I am planning on doing it in a future update. it is planned but not a priority. I don't know how to tell you this but you won't understand when I keep telling you.

You have to do it NOW. You can't just violate copyright law and then say you'll fix it in a future update. That's like stealing a laptop with the excuse that you'll pay for it later.

**Comment by smorenitez** [comment]
Ok.

**Comment by smorenitez** [comment]
Please stop. I'm serious @IAGOnGithub You're seriously annoying

**Comment by smorenitez** [comment]
Closing this issue as i am adding license.

**Comment by Paste11** [comment]
> Closing this issue as i am adding license.

b- but its not done
