### ISSUE TITLE
Bad License

### ISSUE THREAD

**Issue by IAGOnGithub** [smorenitez/Better-EdPuzzle-Skipper#22]
The project's current license is not compliant with the GPL, nor does it provide sufficient attribution to the original author, ading.

**Comment by smorenitez** [comment]
Please tell me what ading has done for me or the edpuzzle hacking community? He has retired for all I care.

**Comment by IAGOnGithub** [comment]
For starters, he wrote the code you are using.

**Comment by smorenitez** [comment]
No. I did not copy it from ading though. I copied code from a github that is no longer updated since 1 year ago and it is this: https://github.com/ASmallYawn/EdpuzzleSkipper/blob/main/script.js So it is not ading.

**Comment by IntelligentPickle** [comment]
Completely ignoring the code being plagarized, the license is **very** unprofessional.

**Comment by IAGOnGithub** [comment]
So you deny stealing ading's GPLed code, but admit to stealing a different person's GPLed code? Are you stupid?

**Comment by smorenitez** [comment]
Your the only person who cares.... and the 3 friends that you dragged here. Legit no one cares. Stop harassing me please.

**Comment by IAGOnGithub** [comment]
The problem is that you are committing a copyright offense. You have also harassed the original maintainers of the code, so your comment about harassment doesn't even make sense.

**Comment by UrkiMimi** [comment]
> No. I did not copy it from ading though. I copied code from a github that is no longer updated since 1 year ago and it is this: https://github.com/ASmallYawn/EdpuzzleSkipper/blob/main/script.js So it is not ading.

You just admitted to copying the code

**Comment by IAGOnGithub** [comment]
That's the funniest part. He thinks he owned me by saying "see? I didn't copy from ading" but he still copied the exact same code under the exact same license.
