### ISSUE TITLE
Not GPL Compliant

### ISSUE THREAD

**Issue by IAGOnGithub** [smorenitez/Better-EdPuzzle-Skipper#24]

**Comment by smorenitez** [comment]
Gtfo

**Comment by IAGOnGithub** [comment]
Please try again, on your own this time.

**Comment by UrkiMimi** [comment]
@smorenitez Choose a different license and stop skidding someone else's code and calling it your own.

**Comment by Urufusan** [comment]
> Gtfo

It's not about you being cringe now, it's about potential theft. Please choose GPL to continue work on your project, because the current "license" is not really compatible with GPL of the original project.
