### ISSUE TITLE
Megathread: Discussions on licensing

### ISSUE THREAD

**Issue by smorenitez** [smorenitez/Better-EdPuzzle-Skipper#27]
Due to spam, any GitHub Issues about licensing will be marked as "not plalnned" for now and will be redirected over here for megathread discussion.

**Comment by IAGOnGithub** [comment]
To be clear, you do not own the video skipping code you are using, yet pretend as if you do. This is not okay.

**Comment by smorenitez** [comment]
I will add the GPL license and crediting tomorrow. Cannot right now.

**Comment by IAGOnGithub** [comment]
Bud, I literally code free projects. I know the ins and outs of API requests. I know how to make a newer, more modern, and more better version of what BS this project is. But I am choosing not to because I am not going to waste my energy because of some developer who cant even spend his energy, 4 hours of his life at most, to code an update. No way that is happening. I already have a barebones patch to the new update, but it's private for a reason. I'm protesting against lazy development like this.

**Comment by dj1ch** [comment]
dude [this](https://github.com/smorenitez/Better-EdPuzzle-Skipper/blob/main/LICENSE) isn't a license. go to the insights tab on github, click on the community standards, and choose the correct GPL license. you gotta remove that one because that's not even a license lmao

**Comment by smorenitez** [comment]
> dude [this](https://github.com/smorenitez/Better-EdPuzzle-Skipper/blob/main/LICENSE) isn't a license. go to the insights tab on github, click on the community standards, and choose the correct GPL license. you gotta remove that one because that's not even a license lmao

Fixed it.

**Comment by IAGOnGithub** [comment]
You still need to provide proper attribution to the original author of the video skipper, as it is not made clear that you are using their code.

**Comment by smorenitez** [comment]
I did it already dumbass

**Comment by IAGOnGithub** [comment]
Adding "vs6k" to a file named "CONTIBUTING.md" is not clear nor sufficient attribution.

**Comment by smorenitez** [comment]
> Adding "vs6k" to a file named "CONTIBUTING.md" is not clear nor sufficient attribution.

THEN HOW ELSE DO I DO IT DUMBASS

**Comment by dj1ch** [comment]
> > dude [this](https://github.com/smorenitez/Better-EdPuzzle-Skipper/blob/main/LICENSE) isn't a license. go to the insights tab on github, click on the community standards, and choose the correct GPL license. you gotta remove that one because that's not even a license lmao
> 
> Fixed it.

at least we have a license, but it needs to be gpl since you used code from a gpl repo. this is how a copyleft license is.

**Comment by IAGOnGithub** [comment]
Consider writing your own code, maybe?

**Comment by IAGOnGithub** [comment]
> > > dude [this](https://github.com/smorenitez/Better-EdPuzzle-Skipper/blob/main/LICENSE) isn't a license. go to the insights tab on github, click on the community standards, and choose the correct GPL license. you gotta remove that one because that's not even a license lmao
> > 
> > 
> > Fixed it.
> 
> at least we have a license, but it needs to be gpl since you used code from a gpl repo. this is how a copyleft license is.

Oh yeah, I forgot about that part. The license of this project also has to be GPL as it is derived from a GPLed project.

**Comment by dj1ch** [comment]
> > Adding "vs6k" to a file named "CONTIBUTING.md" is not clear nor sufficient attribution.
> 
> THEN HOW ELSE DO I DO IT DUMBASS

you write contributing guidelines? like how you can contribute/how to be a good contributor?

**Comment by IAGOnGithub** [comment]
This must be why my high school CS teacher spent hours talking about copyright law.

**Comment by smorenitez** [comment]
Closed. GPL 3 lisense added.

**Comment by dj1ch** [comment]
> Closed. GPL 3 lisense added.

dude why did you copy paste it? just delete the file then add the GPL license from github. there's a reason why github isn't recognizing that license. its so much easier than writing it yourself or copy pasting
