### ISSUE TITLE
Repository as a whole is being handeled unprofessionally

### ISSUE THREAD

**Issue by UrkiMimi** [smorenitez/Better-EdPuzzle-Skipper#36]
This is pretty self-explanatory but a quick rundown is that issues are opened cause of the copied code from this [repository](https://github.com/ASmallYawn/EdpuzzleSkipper/blob/main/script.js) and they end up being closed with no edits being done to mitigate this problem whatsoever.

An example of stolen code is the getCSRF() function being found with no changes inside this program
Original:
```
function init() {
  getCSRF();
}

function getCSRF() {
  var csrfURL = "https://edpuzzle.com/api/v3/csrf";
  httpGet(csrfURL, function(){
    var data = JSON.parse(this.responseText);
    var csrf = data.CSRFToken;
    getAssignment(csrf);
  });
}
```

Copied code
```
function init() { getCSRF(); } function getCSRF() { var csrfURL = "https://edpuzzle.com/api/v3/csrf"; httpGet(csrfURL, function () { var data = JSON.parse(this.responseText); var csrf = data.CSRFToken; getAssignment(csrf); });
```

The only difference is that the code is in one line compared to it spread out. Otherwise, this is stolen with no credit given.

**Comment by dj1ch** [comment]
we tried to convince the kid to put in a license, ofc it was deleted/not credited correctly. i think adding may take down this repo due to the copied code, tho idk if this is correct

**Comment by smorenitez** [comment]
Licensing and crediting contributors took up unnecessary space that makes
the repo overall harder to navigate. It is not a priority at this time to
add such features. As for the code, I made the code. There is no other
practical way to get the EdPuzzle token. Have you never seen duplicate, but
not copied, code on the internet?? Ever??

**Comment by UrkiMimi** [comment]
Ok, it's fine to fork code but at least give credit to the code's original author instead of saying you wrote it which you didn't.

**Comment by smorenitez** [comment]
You know what since i’m banned from the discord i don’t care anymore i’m
going to rebuild my project but it will copy much more of his code. No
point of trying to hide it anymore

**Comment by lvxnull** [comment]
I get why you'd want to steal code but why would you steal something this shit💀

**Comment by dj1ch** [comment]
> You know what since i’m banned from the discord i don’t care anymore i’m going to rebuild my project but it will copy much more of his code. No point of trying to hide it anymore

you literally just admitted to copying the code, theoretically this repo will be taken down
