### ISSUE TITLE
Write better code and seek help

### ISSUE THREAD

**Issue by lvxnull** [smorenitez/Better-EdPuzzle-Skipper#37]
I know you can't write anything better, but at least you could've picked something better to steal💀
XMLHttpRequest and callbacks belong in 2007

**Comment by dj1ch** [comment]
> I know you can't write anything better, but at least you could've picked something better to steal💀
> 
> XMLHttpRequest and callbacks belong in 2007

even more ironic in his "Bud, I literally code free projects" yap that he claimed to understand API requests and such.
