### ISSUE TITLE
can you please explode

### ISSUE THREAD

**Issue by BomberFish** [smorenitez/Better-EdPuzzle-Skipper#40]
thanks

**Comment by smorenitez** [comment]
The mod menu is back online after a DOS attack. Please use auto-updater.js to stay up to date. @BomberFish

**Comment by smorenitez** [comment]
pls star my project btw if u like it

**Comment by BomberFish** [comment]
who said i liked it

**Comment by smorenitez** [comment]
?? I didn't.

**Comment by BomberFish** [comment]
Bud, I literally code free projects. I know the ins and outs of API requests. I know how to make a newer, more modern, and more better version of what BS this project is. But I am choosing not to because I am not going to waste my energy because of some developer who cant even spend his energy, 4 hours of his life at most, to code an update. No way that is happening. I already have a barebones patch to the new update, but it's private for a reason. I'm protesting against lazy development like this.

**Comment by BomberFish** [comment]
well fuck you

**Comment by BomberFish** [comment]
alright enough trolling i give up

**Comment by BomberFish** [comment]
# :trollface:
