### ISSUE TITLE
among us

### ISSUE THREAD

**Issue by BomberFish** [smorenitez/Better-EdPuzzle-Skipper#41]
feliz navidad
![sussy](https://github.com/smorenitez/Better-EdPuzzle-Skipper/assets/87151697/edb03662-a15f-4a85-8054-2975bb402478)

**Comment by smorenitez** [comment]
Dude why did you do this: https://github.com/ading2210/edpuzzle-answers/issues/40
Stop it, it aint cool
Racism is not funny.

**Comment by BomberFish** [comment]
my man that wasnt me :skull:

**Comment by BomberFish** [comment]
i wanna bet this was you lmao

**Comment by smorenitez** [comment]
Its you. Stop lying, We all know you just hate black people with a passion.

**Comment by EnterTheVoid-x86** [comment]
> Its you. Stop lying, We all know you just hate black people with a passion.

This mf is NOT racist. You are straight up delusional.
